services:
  db:
    image: 'postgres:latest'
    restart: always
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d sample_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local